### PR TITLE
Add rtl support

### PR DESCRIPTION
**Pull request by mossiiiiiii**
#23 

I was able to fix this bug with adding rtlSupport props to props list . rtlSupport default value is false 

Screenshot_20190806-092657

### CODE REVIEW

**Comment by AndreiCalazans** [comment]
Hey, thank you.

The code looks correct, I will run tests on it this afternoon. Also, I'll have to run prettier on the changed files, it looks like your IDE might have formatted differently. Nonetheless, this should be easy to merge, I'll deploy a new version once I merge this. Thanks again.

**Comment by mossiiiiiii** [comment]
thank you so much.

**Comment by AndreiCalazans** [comment]
I tested this and it's a bit more complicated than it seems. I will need more time to look over it. Over the weekend I'll put some effort into getting this correct.

**Comment by mossiiiiiii** [comment]
ok, so good, but if you want to know what does work i18Manager , ask me or read the documents .tnx

**Comment by AndreiCalazans** [comment]
@mossiiiiiii I wanted to spend some time in adding RTL support, but that requires me to get a RTL enabled example up to test it out. Would you be able to add a screen with RTL enabled to [this repository](https://github.com/AndreiCalazans/rnTooltipTester) for me to use it as a testing case? That repo is also published in Expo Snack so everyone can test it.

**Comment by mossiiiiiii** [comment]
sure, I can, but I need more time because I'm busy until  Wednesday in next week, but I'll work it after that

**Comment by AndreiCalazans** [comment]
Closing this since it's stale and I don't plan to work on it any time soon.

**Pull request closed without merging**
