### PR TITLE
Added mouse hover event for react-native-web

### PR DESCRIPTION
**Pull request by neerajkh96**
This will add mouse hover events for react-native-web.
It will now show the tooltip popup on the "onMouseEnter" event, and will hide the tooltip on the "onMouseLeave" event.

### CODE REVIEW

**Comment by AndreiCalazans** [comment]
Interesting. Thanks for the contribution. 

I'll have time over the weekend to check it out. Curious, is this all we need to support react-native-web? How did you test this? Did you validate if it causes any regression to React Native?

**Comment by neerajkh96** [comment]
React-native-web setup is altogether a different journey. I followed the steps from the official document to convert the existing mobile project to a web project. 
The link is https://necolas.github.io/react-native-web/docs/?path=/docs/overview-getting-started--page , and my react-native mobile application was successfully able to run on the web browser. 

Rn-tooltip is by default supported in react-native-web. there is no extra setup required for this library to support react-native-web. 

I was using rn-tooltip to show the information popup on the mobile, but there was a requirement to show the tooltip popup on the mouse hover event on the website. So, I have just added mouse hover events in TouchableOpacity. 

`"Did you validate if it causes any regression to React Native?"` I validated in the existing react-native application also, it did not have any impact there.

**Comment by BossBele** [comment]
Tested this on Expo WEB and seems buggy on my end (doesn't fully support web/Expo Web)

**Comment by AndreiCalazans** [comment]
I appreciate the PR but it's not in my intention to extend this library to support web. Feel free to fork it and use your own version. Thank you for understanding.

**Pull request closed without merging**
