### PR TITLE
Now you can change triangle borders width with send props

### PR DESCRIPTION
**Pull request by hakanozkaptan**

### CODE REVIEW

**Comment by AndreiCalazans** [comment]
Hey @hakanozkaptan, thank you very much for the PR, I will have time tomorrow to take a look. At first, I'm thinking maybe we can allow users to customize the pointer(triangle) even more.

**Comment by AndreiCalazans** [comment]
Please rebase and resolve conflicts and I can merge.

**Comment by hakanozkaptan** [comment]
> Please rebase and resolve conflicts and I can merge.

**Comment by AndreiCalazans** [comment]
I extended this idea a bit further here https://github.com/AndreiCalazans/rn-tooltip/pull/47
I'm closing in favor of PR 47. Thank you for your contribution and I'll add your name to the change log.

**Comment by hakanozkaptan** [comment]
> I extended this idea a bit further here #47
> I'm closing in favor of PR 47. Thank you for your contribution and I'll add your name to the change log.

Okey Andrei Thanks.

**Comment by AndreiCalazans** [comment]
V2 is out https://github.com/AndreiCalazans/rn-tooltip/releases

**Pull request closed without merging**
